# Generated by Django 2.0.2 on 2023-06-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='cancha',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='materiales',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
